[package]
name = "diesel_duckdb"
version = "1.1.1"
edition = "2021"

[dependencies]
diesel = { version = "2.2.10", features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"] }
duckdb = { version = "1.3.2", features = ["bundled", "chrono"] }
chrono = "0.4"
